name: split-pro-dev

services:
  postgres:
    image: postgres:16
    container_name: splitpro-db-dev
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    ports:
      - '54321:5432'
    volumes:
      - database:/var/lib/postgresql/data

  minio:
    image: bitnami/minio:latest
    container_name: splitpro-minio-dev
    restart: always
    environment:
      - MINIO_ROOT_USER=${R2_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${R2_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${R2_BUCKET}
    ports:
      - '9100:9000'
      - '9101:9001'
    volumes:
      - minio_data:/bitnami/minio/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  database:
  minio_data:
